### ISSUE TITLE
Refresh causes crash on card game

### ISSUE THREAD

**Issue by OmgzMan** [COsborn2/student-learning-application#37]
When a new word is loaded and the page refreshes the program crashes.

**Comment by OmgzMan** [comment]
It actually crashes on any refresh. Giving this error: "TypeError: Cannot read property 'id' of undefined"

**Comment by Cwhite534** [comment]
@OmgzMan Its because I pass jwt and id data to the  student view using the history. When you refresh it tries to pull that data out of history but because you are on the spelling page the url is different ie the history is different. I'll fix it
